### ISSUE TITLE
Updating badges

### ISSUE THREAD

**Issue by detj** [kosmasgiannis/whatismyip#4]
Do you know how to update the badge on README.md. I thought, it would happen automatically, but its still shows the dependencies out of data badge.

Also, the bitdeli badge at the bottom of the README is not working. I suppose this is because bitdeli has been acquired by AdRoll and so no one's maintaining that.

https://techcrunch.com/2013/06/12/adroll-acquires-bitdeli/

**Comment by kosmasgiannis** [comment]
I have updated the gemnasium badge and now it says that the dependencies are up to date. 

You are right about the bitdeli badge, I guess I have to remove it. 

Thanks again.

**Comment by kosmasgiannis** [comment]
Bitdeli badge removed.
